version: '3.9'
services:
  apidb:
    restart: always
    image: postgres:14.0-alpine
    ports:
      - '5030:5432'
    volumes:
      - apidb:/var/lib/postgresql/data

  nats:
    restart: always
    image: 2.6.2-alpine
    ports:
      - '5040:4222'

  engine-api:
    restart: always
    environment:
      - GIGAMONO_CONFIG_FILE
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - '5050:5050'
    depends_on:
      - authdb

volumes:
  apidb:
